#!/usr/bin/env bash

set -euo pipefail

default_text="URY - University Radio York"
output_device=/dev/null
wait_seconds=10

pid_file=/tmp/radiotext.pid
last_msg_file=/tmp/radiotext.last
messages_file=radiotext.messages

usage () {
    >&2 echo "$(basename $0) command
    
    Commands:
        - start: start the radiotext daemon
        - stop: stop the radiotext daemon
        - now: view what is currently on radiotext
        - live: follow radiotext updates in real time TODO
    "
    exit 1
}

check_running () {
    if [[ ! -f $pid_file ]]; then
        >&2 echo "daemon not running"
        exit 1
    fi
}

output_text () {
    echo -ne "${@}\f" | tee $output_device $last_msg_file > /dev/null
}

display_messages () {
    output_text $default_text
    sleep $wait_seconds
    [[ ! -f $messages_file ]] && return
    while read message; do
        output_text $message
        sleep $wait_seconds
    done < $messages_file
}

daemon () {
    while true; do
        display_messages
        output_text $RANDOM
        sleep 10
    done
}

start_daemon () {
    if [[ -f $pid_file ]]; then
        >&2 echo "daemon already running"
        exit 1
    fi

    touch $last_msg_file

    daemon &
    echo $! > $pid_file
}

stop_daemon () {
    kill $(cat $pid_file)
    rm $pid_file
    output_text $default_text
}

main () {
    [[ $# -ne 1 ]] && usage

    case $1 in
        "start")
            start_daemon
            ;;
        
        "stop")
            check_running
            stop_daemon
            ;;

        "now")
            check_running
            cat $last_msg_file
            ;;

        "live")
            # TODO
            check_running
            cat $last_msg_file
            ;;

        *)
            usage
            ;;
    esac
}

main ${@}